config/routes.rb
Wishlist::Application.routes.draw do
  get 'about/versions'
  get 'about/help'

  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_scope :user do
     get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
     delete 'users/sign_out' => 'devise/sessions#destroy'
  end

  get 'families/missing' => 'family#missing'
  resources :families
  resources :users
  resources :gifts
  resources :user_info
  resources :statuses
  resources :user_notes

  root 'families#index'

  get 'families/:id/birthdays' => 'families#birthdays'

end

app/models/user_note.rb
class UserNote < ActiveRecord::Base

   belongs_to :user

   def to_s
      self.notes
   end

   def check_permissions(user)
      return self.user.check_permissions(user)
   end

   # Ransack configuration for ActiveAdmin
   def self.ransackable_associations(auth_object = nil)
      ["user"]
   end

   def self.ransackable_attributes(auth_object = nil)
      ["notes", "user_id"]
   end

end

app/controllers/user_notes_controller.rb
class UserNotesController < ApplicationController

   def edit
      @note = UserNote.find(params[:id])
      maybe_redirect(@note.check_permissions(current_user))
   end

   def update
      @note = UserNote.find(params[:id])
      maybe_redirect(@note.check_permissions(current_user))

      if @note.update(user_note_params)
         redirect_to user_info_path(User.view_user(session))
      end
   end

   private
   def user_note_params
      params.require(:user_note).permit(:notes)
   end

end

app/views/user_notes/_form.html.erb
<div class="form">
   <%= form_for @note do |f| %>
      <div class="form-group">
         <div class="input-group input-group">
            <span class="input-group-addon">description</span>
            <%= f.text_area :notes, :class => "form-control", :rows => 20, :style => "height: auto" %>
         </div>
      </div>
      <div class="form-group">
         <%= f.submit :class => "btn btn-success" %>
      </div>
   <% end %>
</div>

app/views/user_notes/edit.html.erb
<div class="panel panel-primary">
   <div class="panel-heading"><h2>edit user notes <%= link_to "back to " + @view_user.name, user_path(@view_user), :class => "btn btn-success" %></h2></div>
   <div class="panel-body">
      <%= render partial: 'form', locals: {_target: user_info_url(@note.user), _method: :patch} %>
   </div>
</div>