config/routes.rb
Wishlist::Application.routes.draw do
  get 'about/versions'
  get 'about/help'

  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_scope :user do
     get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
     delete 'users/sign_out' => 'devise/sessions#destroy'
  end

  get 'families/missing' => 'family#missing'
  resources :families
  resources :users
  resources :gifts
  resources :user_info
  resources :statuses
  resources :user_notes

  root 'families#index'

  get 'families/:id/birthdays' => 'families#birthdays'

end

app/controllers/user_info_controller.rb
class UserInfoController < ApplicationController
   before_action :check_view_user

   def show
      id = params[:id]
      @user = User.find(id)
      maybe_redirect(@user.check_permissions(current_user))
      @note = @user.user_note
      if not @note
         @note = UserNote.new(:user_id => id)
         @note.save
      end
      @emails = @user.emails.order(:email)
      @phone_numbers = @user.phone_numbers
      @addresses = @user.addresses
   end

end

app/helpers/user_info_helper.rb
module UserInfoHelper
end

app/views/user_info/show.html.erb
<ol class="breadcrumb">
   <li><%= me_breadcrumb() %></li>
   <li><%= link_to "my families", families_path %></li>
   <li><%= link_to @view_family.name, family_path(@view_family) %></li>
   <li><%= user_breadcrumb(@view_user, current_user, true) %></li>
   <li class="active">user info</li>
</ol>

<strong>birthday:</strong>
<%= @user.birthday %>
<br>
<br>

<strong>note (<%= link_to "edit", edit_user_note_path(@note) %>):</strong>
<%= simple_format(@note.to_s) %>

<% if @view_user.id == current_user.id %>
<strong>pollyannas:</strong>
<br>
<% @view_user.pollyannas.each do |pollyanna| %>
   <% if pollyanna.created_at.year == Time.now.year %>
      <%= "%s %s: %s" % [pollyanna.created_at.year, pollyanna.name, pollyanna.receiver.name] %>
      <br>
   <% end %>
<% end %>
<br>
<% end %>

<strong>e-mail:</strong>
<br>
<% @emails.each do |email| %>
   <%= email.label? ? "%s: %s" % [email.label, email.to_s] : email.to_s %>
   <br>
<% end %>
<br>

<strong>phone:</strong>
<br>
<% @phone_numbers.each do |phone| %>
   <%= phone.label? ? "%s: %s" % [phone.label, phone.to_s] : phone.to_s %>
   <br>
<% end %>
<br>

<strong>address:</strong>
<br>
<% @addresses.each do |address| %>
   <%= address.label? ? "%s: %s" % [address.label, address.to_s] : address.to_s %>
   <br>
<% end %>
<br>

<%= link_to "back to " + @view_user.first_name(), user_path(@view_user), :class => "btn btn-success" %>