config/routes.rb
Wishlist::Application.routes.draw do
  get 'about/versions'
  get 'about/help'

  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_scope :user do
     get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
     delete 'users/sign_out' => 'devise/sessions#destroy'
  end

  get 'families/missing' => 'family#missing'
  resources :families
  resources :users
  resources :gifts
  resources :user_info
  resources :statuses
  resources :user_notes

  root 'families#index'

  get 'families/:id/birthdays' => 'families#birthdays'

end

app/models/gift.rb
class Gift < ActiveRecord::Base
   include LastChanged

   belongs_to :list
   has_many :statuses, dependent: :destroy

   scope :visible, -> (hide_things) { where :hidden != hide_things or !hide_things }

   validates :description, presence: true
   validates :link, url: true 

   after_save :set_last_changed

   def status_summary
      Status.summary(self.statuses)
   end

   def to_s
      "%d: %s" % [self.id, self.description]
   end

   def check_permissions(user)
      return list.check_permissions(user)
   end

   def set_last_changed
      touch :last_change_time
      list.set_last_changed
   end

   def added_status
      return Status.new(:added_by_user_id => self.added_by_user_id, :gift_id => self.id,
                        :note => "gift created", :status => :available,
                        :created_at => self.created_at, :updated_at => self.created_at)
   end

   # Ransack configuration for ActiveAdmin
   def self.ransackable_associations(auth_object = nil)
      ["list", "statuses"]
   end

   def self.ransackable_attributes(auth_object = nil)
      ["description", "link", "list_id", "added_by_user_id", "starred", "hidden", "created_at", "updated_at", "last_change_time"]
   end

end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
   before_action :check_view_user

   def new
      list = List.find(params[:list_id])
      maybe_redirect(list.check_permissions(current_user))
      @gift = Gift.new(:list_id => list.id)
   end

   def create
      @gift = Gift.create(gift_params)
      if @gift.valid?
         redirect_to User.view_user(session)
      else
         render :new
      end
   end

   def edit
      @gift = Gift.find(params[:id])
      maybe_redirect(@gift.check_permissions(current_user))
   end

   def update
      @gift = Gift.find(params[:id])
      maybe_redirect(@gift.check_permissions(current_user))

      if @gift.update(gift_params)
         redirect_to User.view_user(session)
      else
         render 'edit'
      end
   end

   def destroy
      @gift = Gift.find(params[:id])
      maybe_redirect(@gift.check_permissions(current_user))
      @gift.destroy
      redirect_to User.view_user(session)
   end

   private
   def gift_params
      params.require(:gift).permit(:description, :link, :list_id, :added_by_user_id, :starred, :hidden)
   end
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/views/gifts/_form.html.erb
<% hide_things = @gift.list.users.include? current_user %>

<div class="form">
   <%= form_for @gift do |f| %>
      <%= f.hidden_field :list_id, :value => @gift.list_id %>
      <%= f.hidden_field :added_by_user_id, :value => current_user.id %>

      <div class="form-group">
         <div class="checkbox">
            <h3>
               <label><%= f.check_box :starred %><span class="label label-default">really want</span></label>
            </h3>
         </div>

         <% if not hide_things %>
            <div class="checkbox">
               <h3>
                  <label><%= f.check_box :hidden %><span class="label label-default">hidden</span></label>
               </h3>
            </div>
         <% end  %>
      </div>

      <div class="form-group">
         <h3>
            <label class="label label-default" for="description">description</label>
         </h3>
         <%= f.text_field :description, :class => "form-control", :id => "description" %>
      </div>

      <div class="form-group <%= error_for( @gift, :link, "has-error" ) %>">
         <h3>
            <label class="label label-default" for="link">link</label>
         </h3>
         <%= f.text_field :link, :class => "form-control", :id => "link" %>
      </div>

      <div class="form-group">
         <%= f.submit :class => "btn btn-success" %>
      </div>
   <% end %>
</div>

<script>
$('#description').on('paste', function () {
   var element = this;
   setTimeout(function ()
   {
      var text = $(element).val();
      var parts = text.split(" ");
      if(parts.length >= 2)
      {
         var regex = /https?:\/\/[\-A-Za-z0-9+&@#\/%?=~_|$!:,.;]*/g;
         var new_parts = []
         for(part in parts)
         {
            part = parts[part]
            if(part.match(regex))
            {
               $('#link').val(part);
            }
            else
            {
               new_parts.push(part);
            }
         }
         $(element).val(new_parts.join(" "))
      }
   }, 4);
});
</script>

app/views/gifts/_gift.html.erb
<%
   if !hide_things or !gift.hidden
      top_status = gift.status_summary
      summary = top_status ? top_status.status : "available"
      summary_level = Status.statuses[summary]
      summary_label = top_status ? "%s (%s)" % [Status.label(summary), top_status.added_by_user.first_name] : ""
      color = (not hide_things and gift.updated?(current_user)) ? "info" : ""
   %>
   <tr class="<%= color %>">
      <td><%= link_to image_tag('edit.png', alt: "edit this item", height: 16), edit_gift_path(gift.id) %></td>
      <td><%= link_to image_tag('delete.png', alt: "delete this item", height: 16),
         { controller: :gifts, action: :destroy, id: gift.id },
         method: :delete,
         data: { confirm: 'do you really want to delete this?' } %></td>
      <td><%=raw gift.starred? ? "&#9733;" : "" %></td>
      <% if !hide_things %>
         <td class="nowrap" data-sort="<%= summary_level %>">
            <%= link_to image_tag('edit.png', alt: "view or add statuses", height: 16), statuses_path(:gift_id => gift.id) %> <%= raw summary_label %>
         </td>
      <% end %>
      <td>
         <% if gift.hidden %>
            <%= image_tag('hidden.png', alt: "this item is hidden from this person", height: 16) %>
         <% end %>
         <%= gift.description %>
         <% if gift.link? %>
            <a target="_blank" href="<%= gift.link %>">link</a>
         <% end %>
      </td>
   </tr>
<% end %>

app/views/gifts/edit.html.erb
<ol class="breadcrumb">
   <li><%= me_breadcrumb() %></li>
   <li><%= link_to "my families", families_path %></li>
   <li><%= link_to @view_family.name, family_path(@view_family) %></li>
   <li class="active"><%= user_breadcrumb(@view_user, current_user, true) %></li>
   <li><%= link_to "user info", user_info_path(@view_user) %></li>
</ol>

<div class="panel panel-primary">
   <div class="panel-heading"><h2>edit gift <%= link_to "back to " + @view_user.first_name(), user_path(@view_user), :class => "btn btn-success" %></h2></div>
   <div class="panel-body">
      <%= render partial: 'form', locals: {_target: gift_url(@gift), _method: :patch} %>
   </div>
</div>

app/views/gifts/index.html.erb
<h1>Listing gifts</h1>

<%= link_to "donum(us) home", controller: :lists, action: :index %>
<br>
<%= link_to "new gifts", action: :new %>
<br><br>

<table>
   <thead>
   <tr>
      <th>status</th>
      <th>description</th>
      <th>link</th>
   </tr>
   </thead>

   <tbody>
   <% @gifts.each do |gift| %>
      <tr>
         <td><%= gift.status %></td>
         <td><%= gift.description %></td>
         <td><%= gift.link %></td>
         <td><%= link_to 'Show', gift %></td>
         <td><%= link_to 'Edit', edit_gift_path(gift) %></td>
      </tr>
   <% end %>
   </tbody>
</table>

app/views/gifts/new.html.erb
<% if @gift and @gift.errors.any? %>
         <ul class="list-group">
            <li class="list-group-item list-group-item-danger">validation errors</li>
            <% @gift.errors.full_messages.each do |msg| %>
               <li class="list-group-item"><%= msg %></li>
            <% end %>
         </ul>
<% end %>

<ol class="breadcrumb">
   <li><%= me_breadcrumb() %></li>
   <li><%= link_to "my families", families_path %></li>
   <li><%= link_to @view_family.name, family_path(@view_family) %></li>
   <li class="active"><%= user_breadcrumb(@view_user, current_user, true) %></li>
   <li><%= link_to "user info", user_info_path(@view_user) %></li>
</ol>

<div class="panel panel-primary">
   <div class="panel-heading"><h2>new gift <%= link_to "back to " + @view_user.first_name(), user_path(@view_user), :class => "btn btn-success" %></h2></div>
   <div class="panel-body">
      <%= render partial: 'form', locals: {_target: gifts_path, _method: :post} %>
   </div>
</div>

app/views/gifts/show.html.erb
<%= link_to @view_user.name, user_path(user) %>

<%= render @gift %>