config/routes.rb
Wishlist::Application.routes.draw do
  get 'about/versions'
  get 'about/help'

  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_scope :user do
     get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
     delete 'users/sign_out' => 'devise/sessions#destroy'
  end

  get 'families/missing' => 'family#missing'
  resources :families
  resources :users
  resources :gifts
  resources :user_info
  resources :statuses
  resources :user_notes

  root 'families#index'

  get 'families/:id/birthdays' => 'families#birthdays'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <head>
      <title>donum(us)</title>
      <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => "reload" %>
      <%= javascript_include_tag "application", "data-turbolinks-track" => "reload" %>
      <%= csrf_meta_tags %>

      <!-- DataTables CSS -->
      <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.2/css/jquery.dataTables.css">

      <!-- DataTables -->
      <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.2/js/jquery.dataTables.js"></script>

      <!-- Latest compiled and minified CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

      <!-- Optional theme -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

      <!-- Latest compiled and minified JavaScript -->
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

      <%= favicon_link_tag 'gift.png' %>
      <!-- Icon made by <a href="http://www.icomoon.io" title="Icomoon">Icomoon</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> is licensed under <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0">CC BY 3.0</a> -->

      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="apple-mobile-web-app-capable" content="yes">
      <!-- Apple touch icon is in public/images, so reference it directly -->
      <link rel="apple-touch-icon" href="/images/apple-touch-icon-opaque.png">

      <script>
         var LastLocation = "last_location";

         // Mobile Safari in standalone mode
         if(("standalone" in window.navigator) && window.navigator.standalone)
         {

            // If you want to prevent remote links in standalone web apps opening Mobile Safari, change 'remotes' to true
            var noddy, remotes = false;

            document.addEventListener('click', function(event) {

               noddy = event.target;

               // Bubble up until we hit link or top HTML element. Warning: BODY element is not compulsory so better to stop on HTML
               while(noddy.nodeName !== "A" && noddy.nodeName !== "HTML") {
                  noddy = noddy.parentNode;
               }

               if (noddy.nodeName === 'A' && !event.defaultPrevented) {
                  if ('href' in noddy && noddy.target !== '_blank') {
                     document.location.href = noddy.href;
                     event.preventDefault();
                  }
               }

            },false);

            var Root = "/";
            var Families = "/families";
            var last_location = localStorage.getItem(LastLocation);
            if(window.location.pathname == Root && last_location && last_location != Root && last_location != Families)
            {
               window.location.href = last_location;
            }
         }

         localStorage.setItem(LastLocation, "<%= request.fullpath() %>");
      </script>

   </head>

   <body>
      <div class="container-fluid">
         <div class="row">
            <div class="col-sm-6 col-xs-12">
               <h2 class="green">
                  <%= link_to "donum(us)", families_path %><%= link_to image_tag('refresh.png', alt: "refresh", height: 50), request.path %>
               </h2>
            </div>
            <div class="col-sm-6 col-xs-12 text-right">
               <% if current_user %>
                  <div class="row"><div class="col-xs-12"><%= link_to "version 2.5", { :controller => "about", :action => "versions" } %></div></div>
                  <div class="row"><div class="col-xs-12"><%= current_user.name %></div></div>
                  <div class="row"><div class="col-xs-12">(<%= current_user.username %>)</div></div>
                  <div class="row"><div class="col-xs-12"><%= link_to "Log out", users_sign_out_path, method: :delete %></div></div>
               <% end %>
            </div>
         </div>


         <%= yield %>

      </div>
   </body>
</html>